# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 15:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_pki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cert_request',
            name='not_valid_after',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 9, 15, 48, 57, 668740, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cert_request',
            name='token',
            field=models.CharField(db_index=True, default='IJV9YPRIIJMKGU28A543BORIXLYZFM', max_length=50),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='issuer_serial_number',
            field=models.CharField(max_length=250),
        ),
    ]
